/* eslint-disable */
/*Generated by GenDocu.com*/
// source: relay/onboarding/v1/paymentmethods/expressbank.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.displayName = 'proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.displayName = 'proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.toObject = function(includeInstance, msg) {
  var f, obj = {
    partnerId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    productGroupId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    eventRecordPassKey: jspb.Message.getFieldWithDefault(msg, 3, ""),
    financePassKey: jspb.Message.getFieldWithDefault(msg, 4, ""),
    currency: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData;
  return proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPartnerId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setProductGroupId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventRecordPassKey(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFinancePassKey(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrency(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPartnerId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getProductGroupId();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getEventRecordPassKey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFinancePassKey();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCurrency();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional int64 partner_id = 1;
 * @return {number}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.prototype.getPartnerId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.prototype.setPartnerId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 product_group_id = 2;
 * @return {number}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.prototype.getProductGroupId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.prototype.setProductGroupId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string event_record_pass_key = 3;
 * @return {string}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.prototype.getEventRecordPassKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.prototype.setEventRecordPassKey = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string finance_pass_key = 4;
 * @return {string}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.prototype.getFinancePassKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.prototype.setFinancePassKey = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string currency = 5;
 * @return {string}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.prototype.getCurrency = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.InitializeRequestData.prototype.setCurrency = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.toObject = function(includeInstance, msg) {
  var f, obj = {
    partnerId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    productGroupId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    eventRecordPassKey: jspb.Message.getFieldWithDefault(msg, 3, ""),
    financePassKey: jspb.Message.getFieldWithDefault(msg, 4, ""),
    currency: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData;
  return proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPartnerId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setProductGroupId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventRecordPassKey(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFinancePassKey(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrency(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPartnerId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getProductGroupId();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getEventRecordPassKey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFinancePassKey();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCurrency();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional int64 partner_id = 1;
 * @return {number}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.prototype.getPartnerId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.prototype.setPartnerId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 product_group_id = 2;
 * @return {number}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.prototype.getProductGroupId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.prototype.setProductGroupId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string event_record_pass_key = 3;
 * @return {string}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.prototype.getEventRecordPassKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.prototype.setEventRecordPassKey = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string finance_pass_key = 4;
 * @return {string}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.prototype.getFinancePassKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.prototype.setFinancePassKey = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string currency = 5;
 * @return {string}
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.prototype.getCurrency = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.expressbank.UpdateRequestData.prototype.setCurrency = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


goog.object.extend(exports, proto.relay.onboarding.v1.paymentmethods.expressbank);
