/* eslint-disable */
/*Generated by GenDocu.com*/
// package: relay.onboarding.v1.paymentmethods.expressbank
// file: relay/onboarding/v1/paymentmethods/expressbank.proto

import * as jspb from "google-protobuf";

export class InitializeRequestData extends jspb.Message {
  getPartnerId(): number;
  setPartnerId(value: number): void;

  getProductGroupId(): number;
  setProductGroupId(value: number): void;

  getEventRecordPassKey(): string;
  setEventRecordPassKey(value: string): void;

  getFinancePassKey(): string;
  setFinancePassKey(value: string): void;

  getCurrency(): string;
  setCurrency(value: string): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): InitializeRequestData.AsObject;
  static toObject(includeInstance: boolean, msg: InitializeRequestData): InitializeRequestData.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: InitializeRequestData, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): InitializeRequestData;
  static deserializeBinaryFromReader(message: InitializeRequestData, reader: jspb.BinaryReader): InitializeRequestData;
}

export namespace InitializeRequestData {
  export type AsObject = {
    partnerId: number,
    productGroupId: number,
    eventRecordPassKey: string,
    financePassKey: string,
    currency: string,
  }
}

export class UpdateRequestData extends jspb.Message {
  getPartnerId(): number;
  setPartnerId(value: number): void;

  getProductGroupId(): number;
  setProductGroupId(value: number): void;

  getEventRecordPassKey(): string;
  setEventRecordPassKey(value: string): void;

  getFinancePassKey(): string;
  setFinancePassKey(value: string): void;

  getCurrency(): string;
  setCurrency(value: string): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): UpdateRequestData.AsObject;
  static toObject(includeInstance: boolean, msg: UpdateRequestData): UpdateRequestData.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: UpdateRequestData, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): UpdateRequestData;
  static deserializeBinaryFromReader(message: UpdateRequestData, reader: jspb.BinaryReader): UpdateRequestData;
}

export namespace UpdateRequestData {
  export type AsObject = {
    partnerId: number,
    productGroupId: number,
    eventRecordPassKey: string,
    financePassKey: string,
    currency: string,
  }
}

