/* eslint-disable */
/*Generated by GenDocu.com*/
// source: relay/onboarding/v1/paymentmethods/klarna.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
goog.exportSymbol('proto.relay.onboarding.v1.paymentmethods.klarna.Address', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.paymentmethods.klarna.Category', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.paymentmethods.klarna.Roles', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails', null, global);
goog.exportSymbol('proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.repeatedFields_, null);
};
goog.inherits(proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.displayName = 'proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.repeatedFields_, null);
};
goog.inherits(proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.displayName = 'proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.displayName = 'proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.repeatedFields_, null);
};
goog.inherits(proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.displayName = 'proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.relay.onboarding.v1.paymentmethods.klarna.Address, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.paymentmethods.klarna.Address.displayName = 'proto.relay.onboarding.v1.paymentmethods.klarna.Address';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.displayName = 'proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.toObject = function(includeInstance, msg) {
  var f, obj = {
    businessDetails: (f = msg.getBusinessDetails()) && proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.toObject(includeInstance, f),
    storeDetails: (f = msg.getStoreDetails()) && proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.toObject(includeInstance, f),
    stakeholdersDetailsList: jspb.Message.toObjectList(msg.getStakeholdersDetailsList(),
    proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData;
  return proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails;
      reader.readMessage(value,proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.deserializeBinaryFromReader);
      msg.setBusinessDetails(value);
      break;
    case 2:
      var value = new proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails;
      reader.readMessage(value,proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.deserializeBinaryFromReader);
      msg.setStoreDetails(value);
      break;
    case 3:
      var value = new proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails;
      reader.readMessage(value,proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.deserializeBinaryFromReader);
      msg.addStakeholdersDetails(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBusinessDetails();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.serializeBinaryToWriter
    );
  }
  f = message.getStoreDetails();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.serializeBinaryToWriter
    );
  }
  f = message.getStakeholdersDetailsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.serializeBinaryToWriter
    );
  }
};


/**
 * optional BusinessDetails business_details = 1;
 * @return {?proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.prototype.getBusinessDetails = function() {
  return /** @type{?proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails} */ (
    jspb.Message.getWrapperField(this, proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails, 1));
};


/**
 * @param {?proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.prototype.setBusinessDetails = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.prototype.clearBusinessDetails = function() {
  return this.setBusinessDetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.prototype.hasBusinessDetails = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional StoreDetails store_details = 2;
 * @return {?proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.prototype.getStoreDetails = function() {
  return /** @type{?proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} */ (
    jspb.Message.getWrapperField(this, proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails, 2));
};


/**
 * @param {?proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.prototype.setStoreDetails = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.prototype.clearStoreDetails = function() {
  return this.setStoreDetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.prototype.hasStoreDetails = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated StakeholderDetails stakeholders_details = 3;
 * @return {!Array<!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails>}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.prototype.getStakeholdersDetailsList = function() {
  return /** @type{!Array<!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails, 3));
};


/**
 * @param {!Array<!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails>} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.prototype.setStakeholdersDetailsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails=} opt_value
 * @param {number=} opt_index
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.prototype.addStakeholdersDetails = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.InitializeRequestData.prototype.clearStakeholdersDetailsList = function() {
  return this.setStakeholdersDetailsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.toObject = function(includeInstance, msg) {
  var f, obj = {
    businessDetails: (f = msg.getBusinessDetails()) && proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.toObject(includeInstance, f),
    storeDetails: (f = msg.getStoreDetails()) && proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.toObject(includeInstance, f),
    stakeholdersDetailsList: jspb.Message.toObjectList(msg.getStakeholdersDetailsList(),
    proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData;
  return proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails;
      reader.readMessage(value,proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.deserializeBinaryFromReader);
      msg.setBusinessDetails(value);
      break;
    case 2:
      var value = new proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails;
      reader.readMessage(value,proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.deserializeBinaryFromReader);
      msg.setStoreDetails(value);
      break;
    case 3:
      var value = new proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails;
      reader.readMessage(value,proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.deserializeBinaryFromReader);
      msg.addStakeholdersDetails(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBusinessDetails();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.serializeBinaryToWriter
    );
  }
  f = message.getStoreDetails();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.serializeBinaryToWriter
    );
  }
  f = message.getStakeholdersDetailsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.serializeBinaryToWriter
    );
  }
};


/**
 * optional BusinessDetails business_details = 1;
 * @return {?proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.prototype.getBusinessDetails = function() {
  return /** @type{?proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails} */ (
    jspb.Message.getWrapperField(this, proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails, 1));
};


/**
 * @param {?proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.prototype.setBusinessDetails = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.prototype.clearBusinessDetails = function() {
  return this.setBusinessDetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.prototype.hasBusinessDetails = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional StoreDetails store_details = 2;
 * @return {?proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.prototype.getStoreDetails = function() {
  return /** @type{?proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} */ (
    jspb.Message.getWrapperField(this, proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails, 2));
};


/**
 * @param {?proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.prototype.setStoreDetails = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.prototype.clearStoreDetails = function() {
  return this.setStoreDetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.prototype.hasStoreDetails = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated StakeholderDetails stakeholders_details = 3;
 * @return {!Array<!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails>}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.prototype.getStakeholdersDetailsList = function() {
  return /** @type{!Array<!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails, 3));
};


/**
 * @param {!Array<!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails>} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.prototype.setStakeholdersDetailsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails=} opt_value
 * @param {number=} opt_index
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.prototype.addStakeholdersDetails = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.UpdateRequestData.prototype.clearStakeholdersDetailsList = function() {
  return this.setStakeholdersDetailsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: (f = msg.getName()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    registeredAddress: (f = msg.getRegisteredAddress()) && proto.relay.onboarding.v1.paymentmethods.klarna.Address.toObject(includeInstance, f),
    isRegistered: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    registrationId: (f = msg.getRegistrationId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    subjectToVat: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    vatId: (f = msg.getVatId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails;
  return proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setName(value);
      break;
    case 2:
      var value = new proto.relay.onboarding.v1.paymentmethods.klarna.Address;
      reader.readMessage(value,proto.relay.onboarding.v1.paymentmethods.klarna.Address.deserializeBinaryFromReader);
      msg.setRegisteredAddress(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsRegistered(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setRegistrationId(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSubjectToVat(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setVatId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getRegisteredAddress();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.relay.onboarding.v1.paymentmethods.klarna.Address.serializeBinaryToWriter
    );
  }
  f = message.getIsRegistered();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getRegistrationId();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getSubjectToVat();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getVatId();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue name = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.getName = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.setName = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.clearName = function() {
  return this.setName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.hasName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Address registered_address = 2;
 * @return {?proto.relay.onboarding.v1.paymentmethods.klarna.Address}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.getRegisteredAddress = function() {
  return /** @type{?proto.relay.onboarding.v1.paymentmethods.klarna.Address} */ (
    jspb.Message.getWrapperField(this, proto.relay.onboarding.v1.paymentmethods.klarna.Address, 2));
};


/**
 * @param {?proto.relay.onboarding.v1.paymentmethods.klarna.Address|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.setRegisteredAddress = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.clearRegisteredAddress = function() {
  return this.setRegisteredAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.hasRegisteredAddress = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional bool is_registered = 3;
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.getIsRegistered = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.setIsRegistered = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional google.protobuf.StringValue registration_id = 4;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.getRegistrationId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 4));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.setRegistrationId = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.clearRegistrationId = function() {
  return this.setRegistrationId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.hasRegistrationId = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional bool subject_to_vat = 5;
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.getSubjectToVat = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.setSubjectToVat = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional google.protobuf.StringValue vat_id = 6;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.getVatId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 6));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.setVatId = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.clearVatId = function() {
  return this.setVatId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.BusinessDetails.prototype.hasVatId = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    resourceId: (f = msg.getResourceId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    givenName: (f = msg.getGivenName()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    familyName: (f = msg.getFamilyName()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    dateOfBirth: (f = msg.getDateOfBirth()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    address: (f = msg.getAddress()) && proto.relay.onboarding.v1.paymentmethods.klarna.Address.toObject(includeInstance, f),
    personalId: (f = msg.getPersonalId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    rolesList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails;
  return proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setResourceId(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setGivenName(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setFamilyName(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDateOfBirth(value);
      break;
    case 5:
      var value = new proto.relay.onboarding.v1.paymentmethods.klarna.Address;
      reader.readMessage(value,proto.relay.onboarding.v1.paymentmethods.klarna.Address.deserializeBinaryFromReader);
      msg.setAddress(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setPersonalId(value);
      break;
    case 7:
      var values = /** @type {!Array<!proto.relay.onboarding.v1.paymentmethods.klarna.Roles>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addRoles(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResourceId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getGivenName();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getFamilyName();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getDateOfBirth();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getAddress();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.relay.onboarding.v1.paymentmethods.klarna.Address.serializeBinaryToWriter
    );
  }
  f = message.getPersonalId();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getRolesList();
  if (f.length > 0) {
    writer.writePackedEnum(
      7,
      f
    );
  }
};


/**
 * optional google.protobuf.StringValue resource_id = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.getResourceId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.setResourceId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.clearResourceId = function() {
  return this.setResourceId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.hasResourceId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.StringValue given_name = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.getGivenName = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.setGivenName = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.clearGivenName = function() {
  return this.setGivenName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.hasGivenName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.StringValue family_name = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.getFamilyName = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.setFamilyName = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.clearFamilyName = function() {
  return this.setFamilyName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.hasFamilyName = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Timestamp date_of_birth = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.getDateOfBirth = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.setDateOfBirth = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.clearDateOfBirth = function() {
  return this.setDateOfBirth(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.hasDateOfBirth = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Address address = 5;
 * @return {?proto.relay.onboarding.v1.paymentmethods.klarna.Address}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.getAddress = function() {
  return /** @type{?proto.relay.onboarding.v1.paymentmethods.klarna.Address} */ (
    jspb.Message.getWrapperField(this, proto.relay.onboarding.v1.paymentmethods.klarna.Address, 5));
};


/**
 * @param {?proto.relay.onboarding.v1.paymentmethods.klarna.Address|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.setAddress = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.clearAddress = function() {
  return this.setAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.hasAddress = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.StringValue personal_id = 6;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.getPersonalId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 6));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.setPersonalId = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.clearPersonalId = function() {
  return this.setPersonalId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.hasPersonalId = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated Roles roles = 7;
 * @return {!Array<!proto.relay.onboarding.v1.paymentmethods.klarna.Roles>}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.getRolesList = function() {
  return /** @type {!Array<!proto.relay.onboarding.v1.paymentmethods.klarna.Roles>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<!proto.relay.onboarding.v1.paymentmethods.klarna.Roles>} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.setRolesList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.Roles} value
 * @param {number=} opt_index
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.addRoles = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StakeholderDetails.prototype.clearRolesList = function() {
  return this.setRolesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.paymentmethods.klarna.Address.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.Address} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.toObject = function(includeInstance, msg) {
  var f, obj = {
    street: (f = msg.getStreet()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    street2: (f = msg.getStreet2()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    postalCode: (f = msg.getPostalCode()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    city: (f = msg.getCity()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    countryCode: (f = msg.getCountryCode()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    region: (f = msg.getRegion()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.Address}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.paymentmethods.klarna.Address;
  return proto.relay.onboarding.v1.paymentmethods.klarna.Address.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.Address} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.Address}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setStreet(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setStreet2(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setPostalCode(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setCity(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setCountryCode(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setRegion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.paymentmethods.klarna.Address.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.Address} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStreet();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getStreet2();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getPostalCode();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getCity();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getCountryCode();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getRegion();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue street = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.getStreet = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.Address} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.setStreet = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.Address} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.clearStreet = function() {
  return this.setStreet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.hasStreet = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.StringValue street2 = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.getStreet2 = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.Address} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.setStreet2 = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.Address} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.clearStreet2 = function() {
  return this.setStreet2(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.hasStreet2 = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.StringValue postal_code = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.getPostalCode = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.Address} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.setPostalCode = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.Address} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.clearPostalCode = function() {
  return this.setPostalCode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.hasPostalCode = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.StringValue city = 4;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.getCity = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 4));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.Address} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.setCity = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.Address} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.clearCity = function() {
  return this.setCity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.hasCity = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.StringValue country_code = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.getCountryCode = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.Address} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.setCountryCode = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.Address} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.clearCountryCode = function() {
  return this.setCountryCode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.hasCountryCode = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.StringValue region = 6;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.getRegion = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 6));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.Address} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.setRegion = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.Address} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.clearRegion = function() {
  return this.setRegion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Address.prototype.hasRegion = function() {
  return jspb.Message.getField(this, 6) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.toObject = function(opt_includeInstance) {
  return proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: (f = msg.getName()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    url: (f = msg.getUrl()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    category: jspb.Message.getFieldWithDefault(msg, 3, 0),
    countryCode: (f = msg.getCountryCode()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    logoUrl: (f = msg.getLogoUrl()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    iconUrl: (f = msg.getIconUrl()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    featureImageUrl: (f = msg.getFeatureImageUrl()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    facebookUrl: (f = msg.getFacebookUrl()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    instagramUrl: (f = msg.getInstagramUrl()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    adminEmailAddress: (f = msg.getAdminEmailAddress()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    riskEmailAddress: (f = msg.getRiskEmailAddress()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    customerSupportEmailAddress: (f = msg.getCustomerSupportEmailAddress()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    customerSupportPhoneNumber: (f = msg.getCustomerSupportPhoneNumber()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails;
  return proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setName(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setUrl(value);
      break;
    case 3:
      var value = /** @type {!proto.relay.onboarding.v1.paymentmethods.klarna.Category} */ (reader.readEnum());
      msg.setCategory(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setCountryCode(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setLogoUrl(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setIconUrl(value);
      break;
    case 7:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setFeatureImageUrl(value);
      break;
    case 8:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setFacebookUrl(value);
      break;
    case 9:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setInstagramUrl(value);
      break;
    case 10:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setAdminEmailAddress(value);
      break;
    case 11:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setRiskEmailAddress(value);
      break;
    case 12:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setCustomerSupportEmailAddress(value);
      break;
    case 13:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setCustomerSupportPhoneNumber(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getUrl();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getCategory();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getCountryCode();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getLogoUrl();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getIconUrl();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getFeatureImageUrl();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getFacebookUrl();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getInstagramUrl();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getAdminEmailAddress();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getRiskEmailAddress();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getCustomerSupportEmailAddress();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getCustomerSupportPhoneNumber();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue name = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.getName = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.setName = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.clearName = function() {
  return this.setName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.hasName = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.StringValue url = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.getUrl = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.setUrl = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.clearUrl = function() {
  return this.setUrl(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.hasUrl = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Category category = 3;
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.Category}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.getCategory = function() {
  return /** @type {!proto.relay.onboarding.v1.paymentmethods.klarna.Category} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.relay.onboarding.v1.paymentmethods.klarna.Category} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.setCategory = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional google.protobuf.StringValue country_code = 4;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.getCountryCode = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 4));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.setCountryCode = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.clearCountryCode = function() {
  return this.setCountryCode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.hasCountryCode = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.StringValue logo_url = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.getLogoUrl = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.setLogoUrl = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.clearLogoUrl = function() {
  return this.setLogoUrl(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.hasLogoUrl = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.StringValue icon_url = 6;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.getIconUrl = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 6));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.setIconUrl = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.clearIconUrl = function() {
  return this.setIconUrl(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.hasIconUrl = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.StringValue feature_image_url = 7;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.getFeatureImageUrl = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 7));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.setFeatureImageUrl = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.clearFeatureImageUrl = function() {
  return this.setFeatureImageUrl(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.hasFeatureImageUrl = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.StringValue facebook_url = 8;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.getFacebookUrl = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 8));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.setFacebookUrl = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.clearFacebookUrl = function() {
  return this.setFacebookUrl(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.hasFacebookUrl = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.StringValue instagram_url = 9;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.getInstagramUrl = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 9));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.setInstagramUrl = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.clearInstagramUrl = function() {
  return this.setInstagramUrl(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.hasInstagramUrl = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional google.protobuf.StringValue admin_email_address = 10;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.getAdminEmailAddress = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 10));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.setAdminEmailAddress = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.clearAdminEmailAddress = function() {
  return this.setAdminEmailAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.hasAdminEmailAddress = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional google.protobuf.StringValue risk_email_address = 11;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.getRiskEmailAddress = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 11));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.setRiskEmailAddress = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.clearRiskEmailAddress = function() {
  return this.setRiskEmailAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.hasRiskEmailAddress = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional google.protobuf.StringValue customer_support_email_address = 12;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.getCustomerSupportEmailAddress = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 12));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.setCustomerSupportEmailAddress = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.clearCustomerSupportEmailAddress = function() {
  return this.setCustomerSupportEmailAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.hasCustomerSupportEmailAddress = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional google.protobuf.StringValue customer_support_phone_number = 13;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.getCustomerSupportPhoneNumber = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 13));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
*/
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.setCustomerSupportPhoneNumber = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails} returns this
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.clearCustomerSupportPhoneNumber = function() {
  return this.setCustomerSupportPhoneNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.StoreDetails.prototype.hasCustomerSupportPhoneNumber = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * @enum {number}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Category = {
  ADULT_SHOES_AND_CLOTHING: 0,
  AUTOMOTIVE_PARTS_AND_ACCESSORIES: 1,
  BAGS_AND_WALLETS: 2,
  BODY_AND_HAIR_CARE: 3,
  BOOK_AND_MAGAZINES: 4,
  CANDY: 5,
  CAR_ELECTRONICS: 6,
  CHILDREN_CLOTHES_AND_NURTURING_PRODUCTS: 7,
  CHILDREN_TOYS: 8,
  CLEANING_AND_SANITARY: 9,
  COLLECTIBLES: 10,
  CONCEPT_STORES_AND_MISCELLANEOUS: 11,
  COSMETICS: 12,
  COSTUMES_AND_PARTY_SUPPLIES: 13,
  DATING_SERVICES: 14,
  DECORATION_AND_ART: 15,
  DIETARY_SUPPLEMENTS: 16,
  DIGITAL_SERVICES: 17,
  DIVERSIFIED_CHILDREN_PRODUCTS: 18,
  DIVERSIFIED_ELECTRONICS: 19,
  DIVERSIFIED_ENTERTAINMENT: 20,
  DIVERSIFIED_EROTIC_MATERIAL: 21,
  DIVERSIFIED_HOME_AND_GARDEN_PRODUCTS: 22,
  DIVERSIFIED_JEWELRY_AND_ACCESSORIES: 23,
  DIVERSIFIED_HEALTH_AND_BEAUTY_PRODUCTS: 24,
  DIVERSIFIES_HEALTH_AND_BEAUTY_PRODUCTS: 25,
  EDUCATION: 26,
  ELECTRONIC_EQUIPMENT_AND_RELATED_ACCESSORIES: 27,
  EROTIC_CLOTHING_AND_ACCESSORIES: 28,
  EVENT_TICKETS: 29,
  FOOD_AND_BEVERAGE: 30,
  FRAGRANCES: 31,
  FURNITURE: 32,
  GENERAL_SHOES_AND_CLOTHING: 33,
  HOBBY_ARTICLES: 34,
  HOUSEHOLD_ELECTRONICS: 35,
  JEWELRY_AND_WATCHES: 36,
  KITCHENWARE: 37,
  MARKETPLACES: 38,
  MUSIC_AND_MOVIES: 39,
  MUSICAL_INSTRUMENTS_AND_EQUIPMENT: 40,
  NON_PRESCRIPTION_SUNGLASSES_AND_LENSES: 41,
  OFFICE_MACHINES_AND_RELATED_ACCESSORIES: 42,
  OTHER_SERVICES: 43,
  PERSONAL_CARE_AND_BODY_IMPROVEMENT: 44,
  PET_SUPPLIES: 45,
  PHARMACEUTICAL_PRODUCTS: 46,
  PLANTS_AND_FLOWERS: 47,
  PRESCRIPTION_OPTICS: 48,
  PRINTS_AND_PHOTOS: 49,
  SAFETY_PRODUCTS: 50,
  SEX_TOYS: 51,
  SPORTS_GEAR_AND_OUTDOOR: 52,
  TOBACCO: 53,
  TOOLS_AND_HOME_IMPROVEMENT: 54,
  TRAVEL_SERVICES: 55,
  UNDERWEAR: 56,
  VIDEO_GAMES_AND_RELATED_ACCESSORIES: 57,
  WHEELS_AND_TIRES: 58,
  WINE_BEER_AND_LIQUOR: 59,
  YOUTHFUL_SHOES_AND_CLOTHING: 60
};

/**
 * @enum {number}
 */
proto.relay.onboarding.v1.paymentmethods.klarna.Roles = {
  APPLICANT: 0,
  CONTROL_OVER_MANAGEMENT: 1,
  OWNER: 2,
  PARTNER: 3,
  SOLE_TRADER: 4,
  ULTIMATE_BENEFICIAL_OWNER: 5,
  MANAGING_DIRECTOR: 6,
  POLITICALLY_EXPOSED_PERSON: 7,
  MATERIAL_INFLUENCER: 8,
  NOT_APPLICABLE: 9
};

goog.object.extend(exports, proto.relay.onboarding.v1.paymentmethods.klarna);
