// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: relay/processing/v1/paymentmethods/expressbank.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Relay.Processing.V1.PaymentMethods.ExpressBank {

  /// <summary>Holder for reflection information generated from relay/processing/v1/paymentmethods/expressbank.proto</summary>
  public static partial class ExpressbankReflection {

    #region Descriptor
    /// <summary>File descriptor for relay/processing/v1/paymentmethods/expressbank.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExpressbankReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjRyZWxheS9wcm9jZXNzaW5nL3YxL3BheW1lbnRtZXRob2RzL2V4cHJlc3Ni",
            "YW5rLnByb3RvEi5yZWxheS5wcm9jZXNzaW5nLnYxLnBheW1lbnRtZXRob2Rz",
            "LmV4cHJlc3NiYW5rIpABChRBdXRob3JpemVSZXF1ZXN0RGF0YRJpChFwYXlt",
            "ZW50X2Zsb3dfZGF0YRgBIAEoCzJOLnJlbGF5LnByb2Nlc3NpbmcudjEucGF5",
            "bWVudG1ldGhvZHMuZXhwcmVzc2JhbmsuUGF5bWVudEZsb3dSZWRpcmVjdFJl",
            "cXVlc3REYXRhEg0KBWl0ZW1zGAIgAygJIoMBChVBdXRob3JpemVSZXNwb25z",
            "ZURhdGESagoRcGF5bWVudF9mbG93X2RhdGEYASABKAsyTy5yZWxheS5wcm9j",
            "ZXNzaW5nLnYxLnBheW1lbnRtZXRob2RzLmV4cHJlc3NiYW5rLlBheW1lbnRG",
            "bG93UmVkaXJlY3RSZXNwb25zZURhdGEiNwofUGF5bWVudEZsb3dSZWRpcmVj",
            "dFJlc3BvbnNlRGF0YRIUCgxhcHByb3ZhbF91cmwYASABKAkiagoRUmVmdW5k",
            "UmVxdWVzdERhdGESVQoLcmVhc29uX2NvZGUYASABKA4yQC5yZWxheS5wcm9j",
            "ZXNzaW5nLnYxLnBheW1lbnRtZXRob2RzLmV4cHJlc3NiYW5rLlJlZnVuZFJl",
            "YXNvbkNvZGUiSQoeUGF5bWVudEZsb3dSZWRpcmVjdFJlcXVlc3REYXRhEhMK",
            "C3N1Y2Nlc3NfdXJsGAEgASgJEhIKCmZhaWxlZF91cmwYAiABKAkqfAoQUmVm",
            "dW5kUmVhc29uQ29kZRIVChFERUZFQ1RfSU5fUFJPRFVDVBAAEh0KGUNVU1RP",
            "TUVSX0NIQU5HRURfSElTX01JTkQQARIUChBQUk9EVUNUX1JFQ0FMTEVEEAIS",
            "HAoYVEVDSE5JQ0FMX09SX0hVTUFOX0VSUk9SEANCe1pIZ2l0aHViLmNvbS9O",
            "ZWR2ZWQ3NS9ncnBjc2ltcGxlL3Nkay9nby9yZWxheS9wcm9jZXNzaW5nL3Yx",
            "L3BheW1lbnRtZXRob2RzqgIuUmVsYXkuUHJvY2Vzc2luZy5WMS5QYXltZW50",
            "TWV0aG9kcy5FeHByZXNzQmFua2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Relay.Processing.V1.PaymentMethods.ExpressBank.RefundReasonCode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.PaymentMethods.ExpressBank.AuthorizeRequestData), global::Relay.Processing.V1.PaymentMethods.ExpressBank.AuthorizeRequestData.Parser, new[]{ "PaymentFlowData", "Items" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.PaymentMethods.ExpressBank.AuthorizeResponseData), global::Relay.Processing.V1.PaymentMethods.ExpressBank.AuthorizeResponseData.Parser, new[]{ "PaymentFlowData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.PaymentMethods.ExpressBank.PaymentFlowRedirectResponseData), global::Relay.Processing.V1.PaymentMethods.ExpressBank.PaymentFlowRedirectResponseData.Parser, new[]{ "ApprovalUrl" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.PaymentMethods.ExpressBank.RefundRequestData), global::Relay.Processing.V1.PaymentMethods.ExpressBank.RefundRequestData.Parser, new[]{ "ReasonCode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.PaymentMethods.ExpressBank.PaymentFlowRedirectRequestData), global::Relay.Processing.V1.PaymentMethods.ExpressBank.PaymentFlowRedirectRequestData.Parser, new[]{ "SuccessUrl", "FailedUrl" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Express Bank refund reason codes
  /// </summary>
  public enum RefundReasonCode {
    [pbr::OriginalName("DEFECT_IN_PRODUCT")] DefectInProduct = 0,
    [pbr::OriginalName("CUSTOMER_CHANGED_HIS_MIND")] CustomerChangedHisMind = 1,
    [pbr::OriginalName("PRODUCT_RECALLED")] ProductRecalled = 2,
    [pbr::OriginalName("TECHNICAL_OR_HUMAN_ERROR")] TechnicalOrHumanError = 3,
  }

  #endregion

  #region Messages
  public sealed partial class AuthorizeRequestData : pb::IMessage<AuthorizeRequestData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AuthorizeRequestData> _parser = new pb::MessageParser<AuthorizeRequestData>(() => new AuthorizeRequestData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AuthorizeRequestData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentMethods.ExpressBank.ExpressbankReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthorizeRequestData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthorizeRequestData(AuthorizeRequestData other) : this() {
      paymentFlowData_ = other.paymentFlowData_ != null ? other.paymentFlowData_.Clone() : null;
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthorizeRequestData Clone() {
      return new AuthorizeRequestData(this);
    }

    /// <summary>Field number for the "payment_flow_data" field.</summary>
    public const int PaymentFlowDataFieldNumber = 1;
    private global::Relay.Processing.V1.PaymentMethods.ExpressBank.PaymentFlowRedirectRequestData paymentFlowData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Relay.Processing.V1.PaymentMethods.ExpressBank.PaymentFlowRedirectRequestData PaymentFlowData {
      get { return paymentFlowData_; }
      set {
        paymentFlowData_ = value;
      }
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_items_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> items_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Regex: ^.{1,30}$
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AuthorizeRequestData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AuthorizeRequestData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PaymentFlowData, other.PaymentFlowData)) return false;
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (paymentFlowData_ != null) hash ^= PaymentFlowData.GetHashCode();
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (paymentFlowData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PaymentFlowData);
      }
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (paymentFlowData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PaymentFlowData);
      }
      items_.WriteTo(ref output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (paymentFlowData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PaymentFlowData);
      }
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AuthorizeRequestData other) {
      if (other == null) {
        return;
      }
      if (other.paymentFlowData_ != null) {
        if (paymentFlowData_ == null) {
          PaymentFlowData = new global::Relay.Processing.V1.PaymentMethods.ExpressBank.PaymentFlowRedirectRequestData();
        }
        PaymentFlowData.MergeFrom(other.PaymentFlowData);
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (paymentFlowData_ == null) {
              PaymentFlowData = new global::Relay.Processing.V1.PaymentMethods.ExpressBank.PaymentFlowRedirectRequestData();
            }
            input.ReadMessage(PaymentFlowData);
            break;
          }
          case 18: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (paymentFlowData_ == null) {
              PaymentFlowData = new global::Relay.Processing.V1.PaymentMethods.ExpressBank.PaymentFlowRedirectRequestData();
            }
            input.ReadMessage(PaymentFlowData);
            break;
          }
          case 18: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class AuthorizeResponseData : pb::IMessage<AuthorizeResponseData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AuthorizeResponseData> _parser = new pb::MessageParser<AuthorizeResponseData>(() => new AuthorizeResponseData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AuthorizeResponseData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentMethods.ExpressBank.ExpressbankReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthorizeResponseData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthorizeResponseData(AuthorizeResponseData other) : this() {
      paymentFlowData_ = other.paymentFlowData_ != null ? other.paymentFlowData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AuthorizeResponseData Clone() {
      return new AuthorizeResponseData(this);
    }

    /// <summary>Field number for the "payment_flow_data" field.</summary>
    public const int PaymentFlowDataFieldNumber = 1;
    private global::Relay.Processing.V1.PaymentMethods.ExpressBank.PaymentFlowRedirectResponseData paymentFlowData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Relay.Processing.V1.PaymentMethods.ExpressBank.PaymentFlowRedirectResponseData PaymentFlowData {
      get { return paymentFlowData_; }
      set {
        paymentFlowData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AuthorizeResponseData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AuthorizeResponseData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PaymentFlowData, other.PaymentFlowData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (paymentFlowData_ != null) hash ^= PaymentFlowData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (paymentFlowData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PaymentFlowData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (paymentFlowData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PaymentFlowData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (paymentFlowData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PaymentFlowData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AuthorizeResponseData other) {
      if (other == null) {
        return;
      }
      if (other.paymentFlowData_ != null) {
        if (paymentFlowData_ == null) {
          PaymentFlowData = new global::Relay.Processing.V1.PaymentMethods.ExpressBank.PaymentFlowRedirectResponseData();
        }
        PaymentFlowData.MergeFrom(other.PaymentFlowData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (paymentFlowData_ == null) {
              PaymentFlowData = new global::Relay.Processing.V1.PaymentMethods.ExpressBank.PaymentFlowRedirectResponseData();
            }
            input.ReadMessage(PaymentFlowData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (paymentFlowData_ == null) {
              PaymentFlowData = new global::Relay.Processing.V1.PaymentMethods.ExpressBank.PaymentFlowRedirectResponseData();
            }
            input.ReadMessage(PaymentFlowData);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PaymentFlowRedirectResponseData : pb::IMessage<PaymentFlowRedirectResponseData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PaymentFlowRedirectResponseData> _parser = new pb::MessageParser<PaymentFlowRedirectResponseData>(() => new PaymentFlowRedirectResponseData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PaymentFlowRedirectResponseData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentMethods.ExpressBank.ExpressbankReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentFlowRedirectResponseData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentFlowRedirectResponseData(PaymentFlowRedirectResponseData other) : this() {
      approvalUrl_ = other.approvalUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentFlowRedirectResponseData Clone() {
      return new PaymentFlowRedirectResponseData(this);
    }

    /// <summary>Field number for the "approval_url" field.</summary>
    public const int ApprovalUrlFieldNumber = 1;
    private string approvalUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ApprovalUrl {
      get { return approvalUrl_; }
      set {
        approvalUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PaymentFlowRedirectResponseData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PaymentFlowRedirectResponseData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ApprovalUrl != other.ApprovalUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ApprovalUrl.Length != 0) hash ^= ApprovalUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ApprovalUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ApprovalUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ApprovalUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ApprovalUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ApprovalUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ApprovalUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PaymentFlowRedirectResponseData other) {
      if (other == null) {
        return;
      }
      if (other.ApprovalUrl.Length != 0) {
        ApprovalUrl = other.ApprovalUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ApprovalUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ApprovalUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RefundRequestData : pb::IMessage<RefundRequestData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RefundRequestData> _parser = new pb::MessageParser<RefundRequestData>(() => new RefundRequestData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RefundRequestData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentMethods.ExpressBank.ExpressbankReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RefundRequestData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RefundRequestData(RefundRequestData other) : this() {
      reasonCode_ = other.reasonCode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RefundRequestData Clone() {
      return new RefundRequestData(this);
    }

    /// <summary>Field number for the "reason_code" field.</summary>
    public const int ReasonCodeFieldNumber = 1;
    private global::Relay.Processing.V1.PaymentMethods.ExpressBank.RefundReasonCode reasonCode_ = global::Relay.Processing.V1.PaymentMethods.ExpressBank.RefundReasonCode.DefectInProduct;
    /// <summary>
    /// Express Bank refund reason code
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Relay.Processing.V1.PaymentMethods.ExpressBank.RefundReasonCode ReasonCode {
      get { return reasonCode_; }
      set {
        reasonCode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RefundRequestData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RefundRequestData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ReasonCode != other.ReasonCode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ReasonCode != global::Relay.Processing.V1.PaymentMethods.ExpressBank.RefundReasonCode.DefectInProduct) hash ^= ReasonCode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ReasonCode != global::Relay.Processing.V1.PaymentMethods.ExpressBank.RefundReasonCode.DefectInProduct) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ReasonCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ReasonCode != global::Relay.Processing.V1.PaymentMethods.ExpressBank.RefundReasonCode.DefectInProduct) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ReasonCode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ReasonCode != global::Relay.Processing.V1.PaymentMethods.ExpressBank.RefundReasonCode.DefectInProduct) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ReasonCode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RefundRequestData other) {
      if (other == null) {
        return;
      }
      if (other.ReasonCode != global::Relay.Processing.V1.PaymentMethods.ExpressBank.RefundReasonCode.DefectInProduct) {
        ReasonCode = other.ReasonCode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ReasonCode = (global::Relay.Processing.V1.PaymentMethods.ExpressBank.RefundReasonCode) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ReasonCode = (global::Relay.Processing.V1.PaymentMethods.ExpressBank.RefundReasonCode) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PaymentFlowRedirectRequestData : pb::IMessage<PaymentFlowRedirectRequestData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PaymentFlowRedirectRequestData> _parser = new pb::MessageParser<PaymentFlowRedirectRequestData>(() => new PaymentFlowRedirectRequestData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PaymentFlowRedirectRequestData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentMethods.ExpressBank.ExpressbankReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentFlowRedirectRequestData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentFlowRedirectRequestData(PaymentFlowRedirectRequestData other) : this() {
      successUrl_ = other.successUrl_;
      failedUrl_ = other.failedUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentFlowRedirectRequestData Clone() {
      return new PaymentFlowRedirectRequestData(this);
    }

    /// <summary>Field number for the "success_url" field.</summary>
    public const int SuccessUrlFieldNumber = 1;
    private string successUrl_ = "";
    /// <summary>
    /// PaymentId and AuthorizeId are appended as query parameters
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SuccessUrl {
      get { return successUrl_; }
      set {
        successUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "failed_url" field.</summary>
    public const int FailedUrlFieldNumber = 2;
    private string failedUrl_ = "";
    /// <summary>
    /// PaymentId and AuthorizeId are appended as query parameters
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FailedUrl {
      get { return failedUrl_; }
      set {
        failedUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PaymentFlowRedirectRequestData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PaymentFlowRedirectRequestData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SuccessUrl != other.SuccessUrl) return false;
      if (FailedUrl != other.FailedUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SuccessUrl.Length != 0) hash ^= SuccessUrl.GetHashCode();
      if (FailedUrl.Length != 0) hash ^= FailedUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SuccessUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SuccessUrl);
      }
      if (FailedUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FailedUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SuccessUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SuccessUrl);
      }
      if (FailedUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FailedUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SuccessUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SuccessUrl);
      }
      if (FailedUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FailedUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PaymentFlowRedirectRequestData other) {
      if (other == null) {
        return;
      }
      if (other.SuccessUrl.Length != 0) {
        SuccessUrl = other.SuccessUrl;
      }
      if (other.FailedUrl.Length != 0) {
        FailedUrl = other.FailedUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SuccessUrl = input.ReadString();
            break;
          }
          case 18: {
            FailedUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SuccessUrl = input.ReadString();
            break;
          }
          case 18: {
            FailedUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
