// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: relay/processing/v1/paymentmethods/ppro/bancontact.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Relay.Processing.V1.PaymentMethods.Ppro.Bancontact {

  /// <summary>Holder for reflection information generated from relay/processing/v1/paymentmethods/ppro/bancontact.proto</summary>
  public static partial class BancontactReflection {

    #region Descriptor
    /// <summary>File descriptor for relay/processing/v1/paymentmethods/ppro/bancontact.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BancontactReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjhyZWxheS9wcm9jZXNzaW5nL3YxL3BheW1lbnRtZXRob2RzL3Bwcm8vYmFu",
            "Y29udGFjdC5wcm90bxIycmVsYXkucHJvY2Vzc2luZy52MS5wYXltZW50bWV0",
            "aG9kcy5wcHJvLmJhbmNvbnRhY3Qi0gEKEUNoYXJnZVJlcXVlc3REYXRhEm0K",
            "EXBheW1lbnRfZmxvd19kYXRhGAEgASgLMlIucmVsYXkucHJvY2Vzc2luZy52",
            "MS5wYXltZW50bWV0aG9kcy5wcHJvLmJhbmNvbnRhY3QuUGF5bWVudEZsb3dS",
            "ZWRpcmVjdFJlcXVlc3REYXRhEk4KCGNvbnN1bWVyGAIgASgLMjwucmVsYXku",
            "cHJvY2Vzc2luZy52MS5wYXltZW50bWV0aG9kcy5wcHJvLmJhbmNvbnRhY3Qu",
            "Q29uc3VtZXIihAEKEkNoYXJnZVJlc3BvbnNlRGF0YRJuChFwYXltZW50X2Zs",
            "b3dfZGF0YRgBIAEoCzJTLnJlbGF5LnByb2Nlc3NpbmcudjEucGF5bWVudG1l",
            "dGhvZHMucHByby5iYW5jb250YWN0LlBheW1lbnRGbG93UmVkaXJlY3RSZXNw",
            "b25zZURhdGEiSgoIQ29uc3VtZXISDAoEbmFtZRgBIAEoCRIUCgxjb3VudHJ5",
            "X2NvZGUYAiABKAkSGgoScHJlZmVycmVkX2xhbmd1YWdlGAMgASgJInUKHlBh",
            "eW1lbnRGbG93UmVkaXJlY3RSZXF1ZXN0RGF0YRITCgtzdWNjZXNzX3VybBgB",
            "IAEoCRISCgpmYWlsZWRfdXJsGAIgASgJEhIKCmNhbmNlbF91cmwYAyABKAkS",
            "FgoOYXBwX3RvX2FwcF91cmwYBCABKAkiNwofUGF5bWVudEZsb3dSZWRpcmVj",
            "dFJlc3BvbnNlRGF0YRIUCgxhcHByb3ZhbF91cmwYASABKAlChAFaTWdpdGh1",
            "Yi5jb20vTmVkdmVkNzUvZ3JwY3NpbXBsZS9zZGsvZ28vcmVsYXkvcHJvY2Vz",
            "c2luZy92MS9wYXltZW50bWV0aG9kcy9wcHJvqgIyUmVsYXkuUHJvY2Vzc2lu",
            "Zy5WMS5QYXltZW50TWV0aG9kcy5QcHJvLkJhbmNvbnRhY3RiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.ChargeRequestData), global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.ChargeRequestData.Parser, new[]{ "PaymentFlowData", "Consumer" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.ChargeResponseData), global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.ChargeResponseData.Parser, new[]{ "PaymentFlowData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.Consumer), global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.Consumer.Parser, new[]{ "Name", "CountryCode", "PreferredLanguage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.PaymentFlowRedirectRequestData), global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.PaymentFlowRedirectRequestData.Parser, new[]{ "SuccessUrl", "FailedUrl", "CancelUrl", "AppToAppUrl" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.PaymentFlowRedirectResponseData), global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.PaymentFlowRedirectResponseData.Parser, new[]{ "ApprovalUrl" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ChargeRequestData : pb::IMessage<ChargeRequestData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChargeRequestData> _parser = new pb::MessageParser<ChargeRequestData>(() => new ChargeRequestData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChargeRequestData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.BancontactReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChargeRequestData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChargeRequestData(ChargeRequestData other) : this() {
      paymentFlowData_ = other.paymentFlowData_ != null ? other.paymentFlowData_.Clone() : null;
      consumer_ = other.consumer_ != null ? other.consumer_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChargeRequestData Clone() {
      return new ChargeRequestData(this);
    }

    /// <summary>Field number for the "payment_flow_data" field.</summary>
    public const int PaymentFlowDataFieldNumber = 1;
    private global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.PaymentFlowRedirectRequestData paymentFlowData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.PaymentFlowRedirectRequestData PaymentFlowData {
      get { return paymentFlowData_; }
      set {
        paymentFlowData_ = value;
      }
    }

    /// <summary>Field number for the "consumer" field.</summary>
    public const int ConsumerFieldNumber = 2;
    private global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.Consumer consumer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.Consumer Consumer {
      get { return consumer_; }
      set {
        consumer_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChargeRequestData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChargeRequestData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PaymentFlowData, other.PaymentFlowData)) return false;
      if (!object.Equals(Consumer, other.Consumer)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (paymentFlowData_ != null) hash ^= PaymentFlowData.GetHashCode();
      if (consumer_ != null) hash ^= Consumer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (paymentFlowData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PaymentFlowData);
      }
      if (consumer_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Consumer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (paymentFlowData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PaymentFlowData);
      }
      if (consumer_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Consumer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (paymentFlowData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PaymentFlowData);
      }
      if (consumer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Consumer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChargeRequestData other) {
      if (other == null) {
        return;
      }
      if (other.paymentFlowData_ != null) {
        if (paymentFlowData_ == null) {
          PaymentFlowData = new global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.PaymentFlowRedirectRequestData();
        }
        PaymentFlowData.MergeFrom(other.PaymentFlowData);
      }
      if (other.consumer_ != null) {
        if (consumer_ == null) {
          Consumer = new global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.Consumer();
        }
        Consumer.MergeFrom(other.Consumer);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (paymentFlowData_ == null) {
              PaymentFlowData = new global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.PaymentFlowRedirectRequestData();
            }
            input.ReadMessage(PaymentFlowData);
            break;
          }
          case 18: {
            if (consumer_ == null) {
              Consumer = new global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.Consumer();
            }
            input.ReadMessage(Consumer);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (paymentFlowData_ == null) {
              PaymentFlowData = new global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.PaymentFlowRedirectRequestData();
            }
            input.ReadMessage(PaymentFlowData);
            break;
          }
          case 18: {
            if (consumer_ == null) {
              Consumer = new global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.Consumer();
            }
            input.ReadMessage(Consumer);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ChargeResponseData : pb::IMessage<ChargeResponseData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChargeResponseData> _parser = new pb::MessageParser<ChargeResponseData>(() => new ChargeResponseData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChargeResponseData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.BancontactReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChargeResponseData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChargeResponseData(ChargeResponseData other) : this() {
      paymentFlowData_ = other.paymentFlowData_ != null ? other.paymentFlowData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChargeResponseData Clone() {
      return new ChargeResponseData(this);
    }

    /// <summary>Field number for the "payment_flow_data" field.</summary>
    public const int PaymentFlowDataFieldNumber = 1;
    private global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.PaymentFlowRedirectResponseData paymentFlowData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.PaymentFlowRedirectResponseData PaymentFlowData {
      get { return paymentFlowData_; }
      set {
        paymentFlowData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChargeResponseData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChargeResponseData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PaymentFlowData, other.PaymentFlowData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (paymentFlowData_ != null) hash ^= PaymentFlowData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (paymentFlowData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PaymentFlowData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (paymentFlowData_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PaymentFlowData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (paymentFlowData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PaymentFlowData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChargeResponseData other) {
      if (other == null) {
        return;
      }
      if (other.paymentFlowData_ != null) {
        if (paymentFlowData_ == null) {
          PaymentFlowData = new global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.PaymentFlowRedirectResponseData();
        }
        PaymentFlowData.MergeFrom(other.PaymentFlowData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (paymentFlowData_ == null) {
              PaymentFlowData = new global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.PaymentFlowRedirectResponseData();
            }
            input.ReadMessage(PaymentFlowData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (paymentFlowData_ == null) {
              PaymentFlowData = new global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.PaymentFlowRedirectResponseData();
            }
            input.ReadMessage(PaymentFlowData);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Consumer : pb::IMessage<Consumer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Consumer> _parser = new pb::MessageParser<Consumer>(() => new Consumer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Consumer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.BancontactReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Consumer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Consumer(Consumer other) : this() {
      name_ = other.name_;
      countryCode_ = other.countryCode_;
      preferredLanguage_ = other.preferredLanguage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Consumer Clone() {
      return new Consumer(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "country_code" field.</summary>
    public const int CountryCodeFieldNumber = 2;
    private string countryCode_ = "";
    /// <summary>
    /// Format: ISO 3166-1 alpha-3, e.g. NOR, SWE, DNK
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CountryCode {
      get { return countryCode_; }
      set {
        countryCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "preferred_language" field.</summary>
    public const int PreferredLanguageFieldNumber = 3;
    private string preferredLanguage_ = "";
    /// <summary>
    /// Optional - Format: ISO 639-1, e.g. no, se, dk
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PreferredLanguage {
      get { return preferredLanguage_; }
      set {
        preferredLanguage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Consumer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Consumer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (CountryCode != other.CountryCode) return false;
      if (PreferredLanguage != other.PreferredLanguage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (CountryCode.Length != 0) hash ^= CountryCode.GetHashCode();
      if (PreferredLanguage.Length != 0) hash ^= PreferredLanguage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (CountryCode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CountryCode);
      }
      if (PreferredLanguage.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PreferredLanguage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (CountryCode.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CountryCode);
      }
      if (PreferredLanguage.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PreferredLanguage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (CountryCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CountryCode);
      }
      if (PreferredLanguage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PreferredLanguage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Consumer other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.CountryCode.Length != 0) {
        CountryCode = other.CountryCode;
      }
      if (other.PreferredLanguage.Length != 0) {
        PreferredLanguage = other.PreferredLanguage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            CountryCode = input.ReadString();
            break;
          }
          case 26: {
            PreferredLanguage = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            CountryCode = input.ReadString();
            break;
          }
          case 26: {
            PreferredLanguage = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PaymentFlowRedirectRequestData : pb::IMessage<PaymentFlowRedirectRequestData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PaymentFlowRedirectRequestData> _parser = new pb::MessageParser<PaymentFlowRedirectRequestData>(() => new PaymentFlowRedirectRequestData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PaymentFlowRedirectRequestData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.BancontactReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentFlowRedirectRequestData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentFlowRedirectRequestData(PaymentFlowRedirectRequestData other) : this() {
      successUrl_ = other.successUrl_;
      failedUrl_ = other.failedUrl_;
      cancelUrl_ = other.cancelUrl_;
      appToAppUrl_ = other.appToAppUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentFlowRedirectRequestData Clone() {
      return new PaymentFlowRedirectRequestData(this);
    }

    /// <summary>Field number for the "success_url" field.</summary>
    public const int SuccessUrlFieldNumber = 1;
    private string successUrl_ = "";
    /// <summary>
    /// PaymentId and ChargeId are appended as query parameters
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SuccessUrl {
      get { return successUrl_; }
      set {
        successUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "failed_url" field.</summary>
    public const int FailedUrlFieldNumber = 2;
    private string failedUrl_ = "";
    /// <summary>
    /// PaymentId and ChargeId are appended as query parameters
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FailedUrl {
      get { return failedUrl_; }
      set {
        failedUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cancel_url" field.</summary>
    public const int CancelUrlFieldNumber = 3;
    private string cancelUrl_ = "";
    /// <summary>
    /// PaymentId and ChargeId are appended as query parameters
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CancelUrl {
      get { return cancelUrl_; }
      set {
        cancelUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "app_to_app_url" field.</summary>
    public const int AppToAppUrlFieldNumber = 4;
    private string appToAppUrl_ = "";
    /// <summary>
    /// Custom app URL for redirecting the consumer back to the app
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AppToAppUrl {
      get { return appToAppUrl_; }
      set {
        appToAppUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PaymentFlowRedirectRequestData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PaymentFlowRedirectRequestData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SuccessUrl != other.SuccessUrl) return false;
      if (FailedUrl != other.FailedUrl) return false;
      if (CancelUrl != other.CancelUrl) return false;
      if (AppToAppUrl != other.AppToAppUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SuccessUrl.Length != 0) hash ^= SuccessUrl.GetHashCode();
      if (FailedUrl.Length != 0) hash ^= FailedUrl.GetHashCode();
      if (CancelUrl.Length != 0) hash ^= CancelUrl.GetHashCode();
      if (AppToAppUrl.Length != 0) hash ^= AppToAppUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SuccessUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SuccessUrl);
      }
      if (FailedUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FailedUrl);
      }
      if (CancelUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CancelUrl);
      }
      if (AppToAppUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AppToAppUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SuccessUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SuccessUrl);
      }
      if (FailedUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FailedUrl);
      }
      if (CancelUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CancelUrl);
      }
      if (AppToAppUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AppToAppUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SuccessUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SuccessUrl);
      }
      if (FailedUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FailedUrl);
      }
      if (CancelUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CancelUrl);
      }
      if (AppToAppUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppToAppUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PaymentFlowRedirectRequestData other) {
      if (other == null) {
        return;
      }
      if (other.SuccessUrl.Length != 0) {
        SuccessUrl = other.SuccessUrl;
      }
      if (other.FailedUrl.Length != 0) {
        FailedUrl = other.FailedUrl;
      }
      if (other.CancelUrl.Length != 0) {
        CancelUrl = other.CancelUrl;
      }
      if (other.AppToAppUrl.Length != 0) {
        AppToAppUrl = other.AppToAppUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SuccessUrl = input.ReadString();
            break;
          }
          case 18: {
            FailedUrl = input.ReadString();
            break;
          }
          case 26: {
            CancelUrl = input.ReadString();
            break;
          }
          case 34: {
            AppToAppUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SuccessUrl = input.ReadString();
            break;
          }
          case 18: {
            FailedUrl = input.ReadString();
            break;
          }
          case 26: {
            CancelUrl = input.ReadString();
            break;
          }
          case 34: {
            AppToAppUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PaymentFlowRedirectResponseData : pb::IMessage<PaymentFlowRedirectResponseData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PaymentFlowRedirectResponseData> _parser = new pb::MessageParser<PaymentFlowRedirectResponseData>(() => new PaymentFlowRedirectResponseData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PaymentFlowRedirectResponseData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentMethods.Ppro.Bancontact.BancontactReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentFlowRedirectResponseData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentFlowRedirectResponseData(PaymentFlowRedirectResponseData other) : this() {
      approvalUrl_ = other.approvalUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PaymentFlowRedirectResponseData Clone() {
      return new PaymentFlowRedirectResponseData(this);
    }

    /// <summary>Field number for the "approval_url" field.</summary>
    public const int ApprovalUrlFieldNumber = 1;
    private string approvalUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ApprovalUrl {
      get { return approvalUrl_; }
      set {
        approvalUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PaymentFlowRedirectResponseData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PaymentFlowRedirectResponseData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ApprovalUrl != other.ApprovalUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ApprovalUrl.Length != 0) hash ^= ApprovalUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ApprovalUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ApprovalUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ApprovalUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ApprovalUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ApprovalUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ApprovalUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PaymentFlowRedirectResponseData other) {
      if (other == null) {
        return;
      }
      if (other.ApprovalUrl.Length != 0) {
        ApprovalUrl = other.ApprovalUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ApprovalUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ApprovalUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
