// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: relay/onboarding/v1/paymentmethods/expressbank.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Relay.Onboarding.V1.PaymentMethods.ExpressBank {

  /// <summary>Holder for reflection information generated from relay/onboarding/v1/paymentmethods/expressbank.proto</summary>
  public static partial class ExpressbankReflection {

    #region Descriptor
    /// <summary>File descriptor for relay/onboarding/v1/paymentmethods/expressbank.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExpressbankReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjRyZWxheS9vbmJvYXJkaW5nL3YxL3BheW1lbnRtZXRob2RzL2V4cHJlc3Ni",
            "YW5rLnByb3RvEi5yZWxheS5vbmJvYXJkaW5nLnYxLnBheW1lbnRtZXRob2Rz",
            "LmV4cHJlc3NiYW5rIpABChVJbml0aWFsaXplUmVxdWVzdERhdGESEgoKcGFy",
            "dG5lcl9pZBgBIAEoAxIYChBwcm9kdWN0X2dyb3VwX2lkGAIgASgDEh0KFWV2",
            "ZW50X3JlY29yZF9wYXNzX2tleRgDIAEoCRIYChBmaW5hbmNlX3Bhc3Nfa2V5",
            "GAQgASgJEhAKCGN1cnJlbmN5GAUgASgJIowBChFVcGRhdGVSZXF1ZXN0RGF0",
            "YRISCgpwYXJ0bmVyX2lkGAEgASgDEhgKEHByb2R1Y3RfZ3JvdXBfaWQYAiAB",
            "KAMSHQoVZXZlbnRfcmVjb3JkX3Bhc3Nfa2V5GAMgASgJEhgKEGZpbmFuY2Vf",
            "cGFzc19rZXkYBCABKAkSEAoIY3VycmVuY3kYBSABKAlCe1pIZ2l0aHViLmNv",
            "bS9OZWR2ZWQ3NS9ncnBjc2ltcGxlL3Nkay9nby9yZWxheS9vbmJvYXJkaW5n",
            "L3YxL3BheW1lbnRtZXRob2RzqgIuUmVsYXkuT25ib2FyZGluZy5WMS5QYXlt",
            "ZW50TWV0aG9kcy5FeHByZXNzQmFua2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Onboarding.V1.PaymentMethods.ExpressBank.InitializeRequestData), global::Relay.Onboarding.V1.PaymentMethods.ExpressBank.InitializeRequestData.Parser, new[]{ "PartnerId", "ProductGroupId", "EventRecordPassKey", "FinancePassKey", "Currency" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Onboarding.V1.PaymentMethods.ExpressBank.UpdateRequestData), global::Relay.Onboarding.V1.PaymentMethods.ExpressBank.UpdateRequestData.Parser, new[]{ "PartnerId", "ProductGroupId", "EventRecordPassKey", "FinancePassKey", "Currency" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class InitializeRequestData : pb::IMessage<InitializeRequestData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InitializeRequestData> _parser = new pb::MessageParser<InitializeRequestData>(() => new InitializeRequestData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InitializeRequestData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Onboarding.V1.PaymentMethods.ExpressBank.ExpressbankReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitializeRequestData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitializeRequestData(InitializeRequestData other) : this() {
      partnerId_ = other.partnerId_;
      productGroupId_ = other.productGroupId_;
      eventRecordPassKey_ = other.eventRecordPassKey_;
      financePassKey_ = other.financePassKey_;
      currency_ = other.currency_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitializeRequestData Clone() {
      return new InitializeRequestData(this);
    }

    /// <summary>Field number for the "partner_id" field.</summary>
    public const int PartnerIdFieldNumber = 1;
    private long partnerId_;
    /// <summary>
    /// Partner ID code
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PartnerId {
      get { return partnerId_; }
      set {
        partnerId_ = value;
      }
    }

    /// <summary>Field number for the "product_group_id" field.</summary>
    public const int ProductGroupIdFieldNumber = 2;
    private long productGroupId_;
    /// <summary>
    /// Financial product agreement ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ProductGroupId {
      get { return productGroupId_; }
      set {
        productGroupId_ = value;
      }
    }

    /// <summary>Field number for the "event_record_pass_key" field.</summary>
    public const int EventRecordPassKeyFieldNumber = 3;
    private string eventRecordPassKey_ = "";
    /// <summary>
    /// Unique key used in cancel and capture operations
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EventRecordPassKey {
      get { return eventRecordPassKey_; }
      set {
        eventRecordPassKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "finance_pass_key" field.</summary>
    public const int FinancePassKeyFieldNumber = 4;
    private string financePassKey_ = "";
    /// <summary>
    /// Unique key used in refund operations
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FinancePassKey {
      get { return financePassKey_; }
      set {
        financePassKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "currency" field.</summary>
    public const int CurrencyFieldNumber = 5;
    private string currency_ = "";
    /// <summary>
    /// Assigned currency for partner ID. Format: ISO-4217 alpha code, e.g. EUR, USD, GBP
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Currency {
      get { return currency_; }
      set {
        currency_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InitializeRequestData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InitializeRequestData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PartnerId != other.PartnerId) return false;
      if (ProductGroupId != other.ProductGroupId) return false;
      if (EventRecordPassKey != other.EventRecordPassKey) return false;
      if (FinancePassKey != other.FinancePassKey) return false;
      if (Currency != other.Currency) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PartnerId != 0L) hash ^= PartnerId.GetHashCode();
      if (ProductGroupId != 0L) hash ^= ProductGroupId.GetHashCode();
      if (EventRecordPassKey.Length != 0) hash ^= EventRecordPassKey.GetHashCode();
      if (FinancePassKey.Length != 0) hash ^= FinancePassKey.GetHashCode();
      if (Currency.Length != 0) hash ^= Currency.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PartnerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PartnerId);
      }
      if (ProductGroupId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ProductGroupId);
      }
      if (EventRecordPassKey.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EventRecordPassKey);
      }
      if (FinancePassKey.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FinancePassKey);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Currency);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PartnerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PartnerId);
      }
      if (ProductGroupId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ProductGroupId);
      }
      if (EventRecordPassKey.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EventRecordPassKey);
      }
      if (FinancePassKey.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FinancePassKey);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Currency);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PartnerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PartnerId);
      }
      if (ProductGroupId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ProductGroupId);
      }
      if (EventRecordPassKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EventRecordPassKey);
      }
      if (FinancePassKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FinancePassKey);
      }
      if (Currency.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Currency);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InitializeRequestData other) {
      if (other == null) {
        return;
      }
      if (other.PartnerId != 0L) {
        PartnerId = other.PartnerId;
      }
      if (other.ProductGroupId != 0L) {
        ProductGroupId = other.ProductGroupId;
      }
      if (other.EventRecordPassKey.Length != 0) {
        EventRecordPassKey = other.EventRecordPassKey;
      }
      if (other.FinancePassKey.Length != 0) {
        FinancePassKey = other.FinancePassKey;
      }
      if (other.Currency.Length != 0) {
        Currency = other.Currency;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PartnerId = input.ReadInt64();
            break;
          }
          case 16: {
            ProductGroupId = input.ReadInt64();
            break;
          }
          case 26: {
            EventRecordPassKey = input.ReadString();
            break;
          }
          case 34: {
            FinancePassKey = input.ReadString();
            break;
          }
          case 42: {
            Currency = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PartnerId = input.ReadInt64();
            break;
          }
          case 16: {
            ProductGroupId = input.ReadInt64();
            break;
          }
          case 26: {
            EventRecordPassKey = input.ReadString();
            break;
          }
          case 34: {
            FinancePassKey = input.ReadString();
            break;
          }
          case 42: {
            Currency = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class UpdateRequestData : pb::IMessage<UpdateRequestData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateRequestData> _parser = new pb::MessageParser<UpdateRequestData>(() => new UpdateRequestData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateRequestData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Onboarding.V1.PaymentMethods.ExpressBank.ExpressbankReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateRequestData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateRequestData(UpdateRequestData other) : this() {
      partnerId_ = other.partnerId_;
      productGroupId_ = other.productGroupId_;
      eventRecordPassKey_ = other.eventRecordPassKey_;
      financePassKey_ = other.financePassKey_;
      currency_ = other.currency_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateRequestData Clone() {
      return new UpdateRequestData(this);
    }

    /// <summary>Field number for the "partner_id" field.</summary>
    public const int PartnerIdFieldNumber = 1;
    private long partnerId_;
    /// <summary>
    /// Partner ID code
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PartnerId {
      get { return partnerId_; }
      set {
        partnerId_ = value;
      }
    }

    /// <summary>Field number for the "product_group_id" field.</summary>
    public const int ProductGroupIdFieldNumber = 2;
    private long productGroupId_;
    /// <summary>
    /// Financial product agreement ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ProductGroupId {
      get { return productGroupId_; }
      set {
        productGroupId_ = value;
      }
    }

    /// <summary>Field number for the "event_record_pass_key" field.</summary>
    public const int EventRecordPassKeyFieldNumber = 3;
    private string eventRecordPassKey_ = "";
    /// <summary>
    /// Unique key used in cancel and capture operations
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EventRecordPassKey {
      get { return eventRecordPassKey_; }
      set {
        eventRecordPassKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "finance_pass_key" field.</summary>
    public const int FinancePassKeyFieldNumber = 4;
    private string financePassKey_ = "";
    /// <summary>
    /// Unique key used in refund operations
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FinancePassKey {
      get { return financePassKey_; }
      set {
        financePassKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "currency" field.</summary>
    public const int CurrencyFieldNumber = 5;
    private string currency_ = "";
    /// <summary>
    /// Assigned currency for partner ID. Format: ISO-4217 alpha code, e.g. EUR, USD, GBP
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Currency {
      get { return currency_; }
      set {
        currency_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateRequestData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateRequestData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PartnerId != other.PartnerId) return false;
      if (ProductGroupId != other.ProductGroupId) return false;
      if (EventRecordPassKey != other.EventRecordPassKey) return false;
      if (FinancePassKey != other.FinancePassKey) return false;
      if (Currency != other.Currency) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PartnerId != 0L) hash ^= PartnerId.GetHashCode();
      if (ProductGroupId != 0L) hash ^= ProductGroupId.GetHashCode();
      if (EventRecordPassKey.Length != 0) hash ^= EventRecordPassKey.GetHashCode();
      if (FinancePassKey.Length != 0) hash ^= FinancePassKey.GetHashCode();
      if (Currency.Length != 0) hash ^= Currency.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PartnerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PartnerId);
      }
      if (ProductGroupId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ProductGroupId);
      }
      if (EventRecordPassKey.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EventRecordPassKey);
      }
      if (FinancePassKey.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FinancePassKey);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Currency);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PartnerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PartnerId);
      }
      if (ProductGroupId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ProductGroupId);
      }
      if (EventRecordPassKey.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(EventRecordPassKey);
      }
      if (FinancePassKey.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FinancePassKey);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Currency);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PartnerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PartnerId);
      }
      if (ProductGroupId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ProductGroupId);
      }
      if (EventRecordPassKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EventRecordPassKey);
      }
      if (FinancePassKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FinancePassKey);
      }
      if (Currency.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Currency);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateRequestData other) {
      if (other == null) {
        return;
      }
      if (other.PartnerId != 0L) {
        PartnerId = other.PartnerId;
      }
      if (other.ProductGroupId != 0L) {
        ProductGroupId = other.ProductGroupId;
      }
      if (other.EventRecordPassKey.Length != 0) {
        EventRecordPassKey = other.EventRecordPassKey;
      }
      if (other.FinancePassKey.Length != 0) {
        FinancePassKey = other.FinancePassKey;
      }
      if (other.Currency.Length != 0) {
        Currency = other.Currency;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PartnerId = input.ReadInt64();
            break;
          }
          case 16: {
            ProductGroupId = input.ReadInt64();
            break;
          }
          case 26: {
            EventRecordPassKey = input.ReadString();
            break;
          }
          case 34: {
            FinancePassKey = input.ReadString();
            break;
          }
          case 42: {
            Currency = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PartnerId = input.ReadInt64();
            break;
          }
          case 16: {
            ProductGroupId = input.ReadInt64();
            break;
          }
          case 26: {
            EventRecordPassKey = input.ReadString();
            break;
          }
          case 34: {
            FinancePassKey = input.ReadString();
            break;
          }
          case 42: {
            Currency = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
